export const earthInternal = require("./planet-earth-internal.svg")
export const mercuryInternal = require("./planet-mercury-internal.svg")
export const venusInternal = require("./planet-venus-internal.svg")
export const marsInternal = require("./planet-mars-internal.svg")
export const saturnInternal = require("./planet-saturn-internal.svg")
export const jupiterInternal = require("./planet-jupiter-internal.svg")
export const neptuneInternal = require("./planet-neptune-internal.svg")
export const uranusInternal = require("./planet-uranus-internal.svg")

export const earth = require("./planet-earth.svg")
export const mercury = require("./planet-mercury.svg")
export const venus = require("./planet-venus.svg")
export const mars = require("./planet-mars.svg")
export const saturn = require("./planet-saturn.svg")
export const jupiter = require("./planet-jupiter.svg")
export const neptune = require("./planet-neptune.svg")
export const uranus = require("./planet-uranus.svg")

export const earthGeo = require("./geology-earth.png")
export const mercuryGeo = require("./geology-mercury.png")
export const venusGeo = require("./geology-venus.png")
export const marsGeo = require("./geology-mars.png")
export const saturnGeo = require("./geology-saturn.png")
export const jupiterGeo = require("./geology-jupiter.png")
export const neptuneGeo = require("./geology-neptune.png")
export const uranusGeo = require("./geology-uranus.png")
